family_tree/urls.py
from django.contrib import admin
from django.urls import path, include

import fchain.urls as fchain

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fchain.urls')),
]

fchain/urls.py
from django.urls import path

from fchain.views import index, tree_detail, create_tree, delete_tree, \
        add_anggota, add_anggota_pasangan, cari_relasi

urlpatterns = [
    path('', index, name='index'),
    path('tree/', tree_detail, name='tree_detail'),
    path('new_tree/', create_tree, name='create_tree'),
    path('delete_tree/', delete_tree, name='delete_tree'),
    path('add_anggota/', add_anggota, name='add_anggota'),
    path('add_anggota_pasangan/', add_anggota_pasangan,
            name='add_anggota_pasangan'),
    path('cari_relasi/', cari_relasi, name='cari_relasi'),
]

fchain/models.py
from django.db import models

# Create your models here.

# example: Father(x)


class Term(models.Model):

    link = models.CharField(max_length=50)

    def __str__(self):
        return self.link

# example: Father(nama1, nama2) & Father(nama2, nama3) -->
# Grandfather(nama1, nama3)


class Rule(models.Model):

    # term
    term1 = models.ForeignKey(
        Term, on_delete=models.CASCADE, related_name='rules_term1'
    )
    term2 = models.ForeignKey(
        Term, on_delete=models.CASCADE, related_name='rules_term2'
    )

    INDEX_CHOICES = (
        ('first', 0),
        ('second', 1),
        ('special', 2)
    )

    # what needs to be equal
    term1_alike = models.CharField(
        choices=INDEX_CHOICES,
        max_length=20
    )
    term2_alike = models.CharField(
        choices=INDEX_CHOICES,
        max_length=20
    )

    conclusion = models.ForeignKey(
        Term, on_delete=models.CASCADE, related_name='rules_conclusion'
    )


# family tree
class Tree(models.Model):

    name = models.CharField(max_length=50)
    desc = models.CharField(max_length=110, default=None)

    def __str__(self):
        return self.name

# Orang


class Person(models.Model):

    name = models.CharField(max_length=50)

    spouse = models.ForeignKey(
        "Person",
        on_delete=models.SET_NULL,
        related_name='spouse_of',
        null=True
    )
    father = models.ForeignKey(
        "Person",
        on_delete=models.CASCADE,
        related_name='child_father',
        null=True,
        blank=True,
    )
    mother = models.ForeignKey(
        "Person",
        on_delete=models.CASCADE,
        related_name='child_mother',
        null=True,
        blank=True,
    )
    tree = models.ForeignKey(
        Tree,
        on_delete=models.CASCADE,
        related_name='person',
        default=None
    )
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
        default=None
    )
    generation = models.IntegerField(
        default=1
    )

    def __str__(self):
        return self.name


# example: Father(nama1, nama2) --> True
# always proven True


class Sentence(models.Model):

    # person
    person1 = models.ForeignKey(
        Person, on_delete=models.CASCADE, related_name='sentences_person1'
    )
    person2 = models.ForeignKey(
        Person, on_delete=models.CASCADE, related_name='sentences_person2',
        null=True, blank=True, default=None
    )

    # term
    term = models.ForeignKey(
        Term, on_delete=models.CASCADE, related_name='sentences'
    )

    is_displayed = models.BooleanField(default=False)

    tree = models.ForeignKey(
        Tree,
        on_delete=models.CASCADE,
        related_name='sentence',
        default=None
    )

fchain/forms.py
from django import forms
from fchain.models import Term, Rule, Sentence, Person, Tree

CSS_CLASS = 'form-control bg-light'
REQUIRED_MSG = 'Harus diisi'

ORANG1_CHOICES = (
    (1, "Not relevant"),
    (2, "Review"),
    (3, "Maybe relevant"),
    (4, "Relevant"),
    (5, "Leading candidate")
)
ORANG2_CHOICES = (
    (1, "Unread"),
    (2, "Read")
)

class ChoiceForm(forms.Form):
    def __init__(self,*args,**kwargs):
        self.id = kwargs.pop('id')

        tree = Tree.objects.get(id=self.id)
        keluarga = Person.objects.filter(tree=tree)
        list_keluarga = []
        for i in keluarga:
            t_keluarga = (i.name,i.name)
            list_keluarga.append(t_keluarga)
        choices_list = tuple(list_keluarga)
        super(ChoiceForm,self).__init__(*args,**kwargs)
        self.fields['orang_pertama'].choices = choices_list
        self.fields['orang_kedua'].choices = choices_list

    orang_pertama = forms.ChoiceField(label="Nama orang satu",
                                initial='',
                                widget=forms.Select(attrs={'class':CSS_CLASS}),
                                required=True)

    orang_kedua = forms.ChoiceField(label="Nama orang dua",
                                initial='',
                                widget=forms.Select(attrs={'class':CSS_CLASS}),
                                required=True)

fchain/views.py
import os
import csv
from django.contrib import messages
from django.conf import settings
from django.shortcuts import render, redirect, reverse
from fchain.models import Term, Rule, Sentence, Person, Tree
from fchain.forward_chain import forward_chain
from fchain.anggota_form import AnggotaForm
from fchain.forms import ChoiceForm
from fchain.form_pasangan import PasanganForm
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

response = {}
choices_list = ()


def populate_database():

    rule_file = os.path.join(settings.BASE_DIR, 'csv/rules.csv')
    term_file = os.path.join(settings.BASE_DIR, 'csv/terms.csv')

    if not Term.objects.all().count():
        with open(term_file) as csv_file:
            csv_reader = csv.reader(csv_file, delimiter=',')
            for row in csv_reader:
                term = Term.objects.create(link=row[0])

    if not Rule.objects.all().count():
        with open(rule_file) as csv_file:
            csv_reader = csv.reader(csv_file, delimiter=',')
            for row in csv_reader:
                term1 = Term.objects.filter(link=row[0])[0]
                term2 = Term.objects.filter(link=row[1])[0]
                conclusion = Term.objects.filter(link=row[4])[0]

                term1_alike = Rule.INDEX_CHOICES[int(row[2])][0]
                term2_alike = Rule.INDEX_CHOICES[int(row[3])][0]

                rule = Rule.objects.create(
                    term1_id=term1.id,
                    term2_id=term2.id,
                    term1_alike=term1_alike,
                    term2_alike=term2_alike,
                    conclusion_id=conclusion.id
                )


def index(request):
    populate_database()
    tree = Tree.objects.all()
    response = {'tree': tree}
    html = 'index.html'
    return render(request, html, response)


def create_tree(request):

    if request.method == 'POST' \
            and len(Tree.objects.filter(name=request.POST['treename'])) == 0:

        tree_desc = request.POST['granpa']+" "+request.POST['granma']
        tree = Tree.objects.create(
            name=request.POST['treename'],
            desc=tree_desc)
        tree.save()

        granpa = Person.objects.create(name=request.POST['granpa'],
                                       gender='M',
                                       tree=tree)
        granpa.save()

        sentence_save(granpa, "male", tree)

        granma = Person.objects.create(name=request.POST['granma'],
                                       gender='F',
                                       spouse=granpa,
                                       tree=tree)
        granma.save()

        sentence_save(granma, "female", tree)

        granpa.spouse = granma
        granpa.save()

        sentence_save_(granpa, granma, "husband", tree)
        sentence_save_(granma, granpa, "wife", tree)

        messages.success(request, "Pohon Keluarga Berhasil Ditambahkan")
    else:
        messages.warning(request, "Pohon Keluarga Tidak Berhasil Ditambahkan")

    return redirect(reverse('index'))


def delete_tree(request):
    id = request.GET.get('id', None)

    if id is not None:
        tree = Tree.objects.get(id=id)
        tree.delete()
        messages.success(request, "Pohon Keluarga Berhasil Dihapus")
    else:
        messages.warning(request, "Pohon Keluarga Tidak Ada")

    return redirect(reverse('index'))

# https://codepen.io/Pestov/pen/BLpgm


def tree_detail(request):
    tree_id = request.GET.get('id', None)

    tree = Tree.objects.get(id=tree_id)
    keluarga = Person.objects.filter(tree=tree)
    keluarga_only_male = Person.objects.filter(tree=tree,gender='M')

    anggota_form = AnggotaForm(tree)
    search_form = ChoiceForm(id=tree_id)
    pasangan_form = PasanganForm(tree)
    response = {
        'tree': tree,
        'keluarga': keluarga,
        'keluarga_only_male': keluarga_only_male,
        'form': anggota_form,
        'forms': search_form,
        'spouse_form': pasangan_form
        }
    html = 'tree.html'
    return render(request, html, response)


def add_anggota(request):
    id = request.GET.get('id', None)
    tree = Tree.objects.get(id=id)

    if request.method == 'POST':
        # print(request.POST)
        father = Person.objects.get(tree=tree, name=request.POST['parent'])
        gender = 'female' if request.POST['gender'] == 'F' else 'male'

        if father is not None and father.generation < 3:
            new = Person.objects.create(name=request.POST['name'],
                                        father=father,
                                        mother=father.spouse,
                                        gender=request.POST['gender'],
                                        generation=father.generation + 1,
                                        tree=tree)
            new.save()

            sentence_save(new, gender, tree)
            sentence_save_(father, new, 'father', tree)
            sentence_save_(father.spouse, new, 'mother', tree)

            messages.success(request, "Anggota Keluarga Berhasil Ditambahkan")
        else:
            messages.warning(request, "Anggota Keluarga Tidak Berhasil Ditambahkan")
    else:
        messages.warning(request, "Anggota Keluarga Tidak Berhasil Ditambahkan")
    return redirect('/tree/?id={}'.format(id))

def add_anggota_pasangan(request):
    id = request.GET.get('id', None)

    if request.method == 'POST' and len(request.POST) > 3:
        # print(request.POST)
        tree = Tree.objects.get(id=id)
        spouse = Person.objects.get(tree=tree, name=request.POST['pasangan'])
        gender = 'female' if request.POST['gender'] == 'F' else 'male'

        if spouse is not None and spouse.gender != request.POST['gender']:
            new = Person.objects.create(name=request.POST['name'],
                                        spouse=spouse,
                                        gender=request.POST['gender'],
                                        generation=spouse.generation,
                                        tree=tree)
            new.save()
            spouse.spouse = new
            spouse.save()

            sentence_save(new, gender, tree)

            husband = sentence_save_(spouse, new, "husband", tree) if gender=='female'  else sentence_save_(new, spouse, "husband", tree)
            wife = sentence_save_(spouse, new, "wife", tree) if gender=='male'  else sentence_save_(new, spouse, "wife", tree)

            messages.success(request, "Anggota Keluarga Berhasil Ditambahkan")
        else:
            messages.warning(request, "Anggota Keluarga Tidak Berhasil Ditambahkan")
    else:
        messages.warning(request, "Anggota Keluarga Tidak Berhasil Ditambahkan")
    return redirect('/tree/?id={}'.format(id))

@csrf_exempt
def cari_relasi(request):
    id = request.GET.get('id', None)
    data = {}
    if request.method == 'POST':
        tree = Tree.objects.get(id=id)
        hasil = forward_chain(request.POST['orang_pertama'],
                            request.POST['orang_kedua'],
                            tree.id)
        #messages.success(request, hasil)
        data = {'hasil':hasil}
    return JsonResponse(data)
    #return redirect('/tree/?id={}'.format(id))

def sentence_save(person, link, tree):
    term = Term.objects.filter(link=link).first()
    person_sentence = Sentence.objects.create(
        person1=person, term=term, tree=tree)
    person_sentence.save()
    return person_sentence

def sentence_save_(person1, person2, link, tree):
    term = Term.objects.filter(link=link).first()
    sentence = Sentence.objects.create(
        person1=person1, person2=person2,
        term=term, tree=tree)
    sentence.save()
    return sentence

fchain/templates/index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <main role="main" class="container">
        <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
            <img class="mr-3" src="https://image.ibb.co/fzA0uf/images.jpg" alt="" width="48" height="48" style="border-radius: 30%;">
            <div class="lh-100">
                <h6 class="mb-0 text-white lh-100">Sahabat Cerdas</h6>
                <small>Sistem Cerdas - C | Ganjil 2018</small><br>
                <small>Aldi Hilman Ramadhani (1606895184) | Izzatul Muttaqin (1606837915) | Muhammad Ilham Peruzzi (1606823475)</small>
            </div>
        </div>

        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        <div class="container">
            <div class="row">
                <div class="col-8">

                    <div class="my-3 p-3 bg-white rounded shadow-sm">
                        <h6 class="border-bottom border-gray pb-2 mb-0">Family Tree</h6>

                        {% if tree %}
                        {% for tree_name in tree %}
                        <div class="media text-muted pt-3">
                            <a href="{% url 'tree_detail' %}?id={{ tree_name.id }}">
                                <img src="https://i.pinimg.com/originals/39/2c/7b/392c7bceff54fef590ba1d0d4cdf5632.png"
                                    alt="" class="mr-2 rounded" height="48" width="48">
                                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                                    <div class="d-flex justify-content-between align-items-center w-100">
                                        <strong class="text-gray-dark">{{ tree_name.name }}</strong>
                                        <a data-toggle="modal" data-target="#confirm" class="btn btn-danger" href="{% url 'delete_tree' %}?id={{ tree_name.id }}">Delete</a>
                                    </div>
                                    <span class="d-block">{{ tree_name.desc }}</span>
                                </div>
                            </a>
                        </div>
                        <div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-labelledby="confirmDataModal" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Konfirmasi</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Hapus pohon keluarga ini ? Pohon yang dihapus tidak dapat dikembalikan
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                        <a id="confirm-btn" class="btn btn-primary" href="{% url 'delete_tree' %}?id={{ tree_name.id }}">Ya</a>
                    </div>
                </div>
            </div>
        </div>
                        {% endfor %}
                        
                        {% else %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            Tidak ada Tree
        </div>

                        {% endif %}


                    </div>

                </div>

                <div class="col-4">
                    <div class="my-3 p-3 bg-white rounded shadow-sm">
                        <h6 class="border-bottom border-gray pb-2 mb-0">Tambah Pohon</h6>
                        <form action="{% url 'create_tree' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="bg-light form-control" name="treename" placeholder="Nama pohon"
                                   required>
                            </div>
                            <div class="form-group">
                                <input type="text" class="bg-light form-control" name="granpa" placeholder="Nama kakek"
                                    required>
                            </div>
                            <div class="form-group">
                                <input type="text" class="bg-light form-control" name="granma" placeholder="Nama nenek"
                                    required>
                            </div>
                            <button type="submit" class="btn btn-primary my-2">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

</main>
{% endblock %}

fchain/templates/tree.html
{% extends "base.html" %}
{% load static %}


{% block content %}
      <div id="loader"></div>
      <main role="main" class="container" id="body_container" >
         <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm" style="margin-right: 26px;margin-left: 15px">
            <img class="mr-3" src="https://i.pinimg.com/originals/39/2c/7b/392c7bceff54fef590ba1d0d4cdf5632.png" alt="" width="48" height="48" style="border-radius: 30%;">
            <div class="lh-100">
               <h6 class="mb-0 text-white lh-100">{{ tree.name }}</h6>
               <small>{{ tree.desc }}</small>
            </div>
         </div>

        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

         

         <div class="container">
            <div class="row">
              <div class="col-6">
                 <div class="p-3 bg-white rounded shadow-sm">
                     <h2 class="border-bottom border-gray pb-2 mb-0">Premis</h2>
                     <div class="media text-muted pt-3">
                        <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                          <ul>
                            <li><h6>
                              Pohon keluarga {{ tree.name }} memiliki anggota keluarga sebagai berikut:
                              <br>{% if keluarga %}
                                {% for anggota in keluarga %}
                                  {{ anggota.name }};
                                {% endfor %}
                              {% endif %}
                            </h6></li>

                            {% if keluarga %}
                              {% for anggota in keluarga_only_male %}
                                {% if anggota.spouse %}
                                <li><h6>
                                  {{ anggota.name }} memiliki pasangan {{ anggota.spouse }}
                                </h6></li>
                                {% endif %}
                              {% endfor %}
                            {% endif %}

                            {% if keluarga %}
                              {% for anggota in keluarga %}
                                {% if anggota.father %}
                                <li><h6>
                                  {{ anggota.name }} merupakan anak dari pasangan {{ anggota.father }} dan {{ anggota.mother }}
                                </h6></li>
                                {% endif %}
                              {% endfor %}
                            {% endif %}

                          </ul>
                        </div>
                     </div>
                  </div>
              </div>

               <div class="col-6">
                  <div class="container">
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#anggota">Tambah Anggota</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#pasangan">Tambah Pasangan</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#relasi">Cari Relasi</a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div id="anggota" class="container tab-pane active bg-white shadow-sm"><br>
      <div >
                   
                   <form action="{% url 'add_anggota' %}?id={{ tree.id }}" method="post">
                     {% csrf_token %}
                     {% for field in form %}
                      <div class="form-group" id="div_{{ field.name }}">
                          {{ field.label_tag }}
                          {{ field }}
                      </div>
                      {% endfor %}
                     <button type="submit" class="btn btn-primary my-2">Submit</button>
                   </form>
                 </div>
    </div>
    <div id="pasangan" class="container tab-pane fade bg-white shadow-sm"><br>
      <div>
                    <form action="{% url 'add_anggota_pasangan' %}?id={{ tree.id }}" method="post">
                      {% csrf_token %}
                      {% for field in spouse_form %}
                       <div class="form-group" id="div_{{ field.name }}">
                           {{ field.label_tag }}
                           {{ field }}
                       </div>
                       {% endfor %}
                      <button type="submit" class="btn btn-primary my-2">Submit</button>
                    </form>
      </div>
    </div>
    <div id="relasi" class="container tab-pane fade bg-white rounded shadow-sm"><br>
      <div>
                    <form id="relasi_form" action="#" method="post">
                      {% csrf_token %}
                      {{ forms }}
                      <button type="submit" class="btn btn-primary my-2">Submit</button>
                    </form>
        </div>
    </div>
  </div>
</div>
               </div>
            </div>
         </div>


      </main>

      <div class="modal fade" id="info_relasi" tabindex="-1" role="dialog" aria-labelledby="confirmDataModal" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Hasil Pencarian Relasi</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div id= modal-body-relasi class="modal-body">
                         
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

{% block javascript %}
    <script>
    $( document ).ready(function () {
      $("#loader").hide();
      $("#relasi_form").on("submit", function (e) {
        e.preventDefault();
        orang1 = $("#id_orang_pertama").val()
        orang2 = $("#id_orang_kedua").val()
        console.log(orang1)
        console.log(orang2)
        $.ajax({
                method: "POST",
                url: '{% url "cari_relasi" %}?id={{ tree.id }}',
                data: {'orang_pertama':orang1, 'orang_kedua':orang2},
                dataType: 'json',
                beforeSend: function(){
                  console.log("Oke")
               // Show image container
                  $('#loader').show();
                  $('#body_container').css('opacity',0.5);
                },
                success : function (response){
                    console.log(response)
                    $('#body_container').css('opacity',1);
                    $('#loader').hide();
                    $("#info_relasi .modal-body").text(response.hasil);
                    $('#info_relasi').modal('show');
                },
            }); 
    });
    });
    </script>
{% endblock %}